#!/bin/bash
outFile=$1

# Takes an input file and removes all sentences
# starting with noise words
# Handles exceptions if the arguments are unreable 
# Authors: Gloire Rubambiza, Kyle Hekhuis
# Version: 04/04/2017

while read line
do
	echo $line >> $outFile
done
sort -uo $1 $1
