#!/bin/bash

# Takes an input file and removes all sentences
# starting with noise words
# Handles exceptions if the arguments are unreable
# Authors: Gloire Rubambiza, Kyle Hekhuis
# Version: 04/04/2017

if test $# -eq 0
  then
		  echo "Must provide arguments to script"
			exit 1
fi

if ! test -f "$1"
  then
	    echo "$1 is not a file in current directory"
			echo "Please provide a valid input"
			exit 1
	elif ! test -r "$1" -o ! test -e "$1"
	   then
			   echo "Please provide a readable/non-empty file"
fi

filterFile=$1
while read line
do
	set $line
	if ! grep -q $1 $filterFile
		then
			echo $line
	fi
done
