#!/bin/bash

while read line
do
	#echo $line
	set $line
	head=$1
	origHead=$1
	shift
	newline="$* $head"
	echo $newline
	set $newline
	while [ "$1" != "$origHead" ]
	do
		head=$1
		shift
		newline="$* $head"
		echo $newline
		set $newline
	done
done
